name: dotnet package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: pwd
        shell: bash
      - run: ls
        shell: bash
      - uses: game-ci/unity-builder@v4.2.3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows
          projectPath: ./
          unityVersion: 2022.3.16f1 
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
