name: Build Windows

on:
  push:
    branch : [ 'main' ]

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/release')
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: echo ${{ github.ref }}
        shell: bash
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - run: pwd
        shell: bash
      - run: ls
        shell: bash
      - uses: game-ci/unity-builder@v4.2.3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows 
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
